<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alt_loginfailed</name>
   <tag></tag>
   <elementGuidId>5189d5e4-3351-48af-ba9b-6bf6cb6bcbcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1yp9wxg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ad1fa25-04bf-41cd-a16b-948edd771709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>03aa0005-a89e-45f0-b3f3-1f42fe13a209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yp9wxg</value>
      <webElementGuid>795287e6-cd8f-4d22-8505-c1e13699c005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validation Error!Email is not valid. Please check again!</value>
      <webElementGuid>e5b52ccd-15f7-417a-97ae-24625a7633d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1jxfye&quot;]/div[@class=&quot;css-1yp9wxg&quot;]</value>
      <webElementGuid>7b84e460-abce-4cf0-88aa-50f0a6ae991a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='error']</value>
      <webElementGuid>ff57c2ea-4600-481e-868d-0b450b1ec1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>b8f427f1-7dae-4ffa-8168-385d4db64262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/preceding::div[15]</value>
      <webElementGuid>8c151bbc-229c-4b3b-bd3d-289ca860edba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>3d0023a0-945e-4ae8-97ca-71ec26708d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and (text() = 'Validation Error!Email is not valid. Please check again!' or . = 'Validation Error!Email is not valid. Please check again!')]</value>
      <webElementGuid>b6aeb5b4-b0f4-42fe-bd91-0b148d3371ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validation Error!'])[2]/preceding::div[3]</value>
      <webElementGuid>fc95f226-0291-4644-ac3d-5b3e10d3a73c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
