<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_loginfailed</name>
   <tag></tag>
   <elementGuidId>50abcc73-a479-4253-8c97-81664a2db32f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[1]/h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[1]/h3</value>
      <webElementGuid>9950c172-97d2-4661-8cdd-4271947a33b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
