<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pop_emailinvalid</name>
   <tag></tag>
   <elementGuidId>90c7d184-407d-46a1-b02c-016d05b05f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1yp9wxg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da3978e2-b7df-4a38-b429-e178ffb3fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>d6fd818c-bce8-40c0-81e9-653e395fa725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yp9wxg</value>
      <webElementGuid>d4626c77-8297-40a4-8703-28eb0658612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validation Error!Email is not valid. Please check again!</value>
      <webElementGuid>917098e6-6045-4f53-95fd-669b597a3eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1jxfye&quot;]/div[@class=&quot;css-1yp9wxg&quot;]</value>
      <webElementGuid>88ecba41-fd64-4b29-9c2d-e11052fb751b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='error']</value>
      <webElementGuid>54df92d7-9d35-4829-8cd6-552289a13c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>d8869365-db7e-412f-bb30-b5e6b74f5791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/preceding::div[15]</value>
      <webElementGuid>e3052eb7-d8f4-4fa5-829c-552f92d584eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>8d13aa03-28de-4691-a7c7-8d88e999eb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and (text() = 'Validation Error!Email is not valid. Please check again!' or . = 'Validation Error!Email is not valid. Please check again!')]</value>
      <webElementGuid>12b922a0-fc8f-43d2-b8b6-1bcfbb7da6e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
