<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pop_passwordrequired</name>
   <tag></tag>
   <elementGuidId>342db184-56fa-4d13-83a9-9036a3e3b762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1yp9wxg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3271fb90-8aad-44a7-86dc-cb6e2c8eda3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>f774b1ee-52c2-4ab7-85fd-6ce3d852fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yp9wxg</value>
      <webElementGuid>47652537-8689-44fe-8174-a0466b5b040a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validation Error!Password required, minimum 6 characters.</value>
      <webElementGuid>cf0214f0-b7db-4b6c-a114-d3428d641e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1jxfye&quot;]/div[@class=&quot;css-1yp9wxg&quot;]</value>
      <webElementGuid>0c705870-2767-4cba-80bb-162815d35f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='error']</value>
      <webElementGuid>b7430e89-7856-4c6f-a4d6-5ef94c45aa21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>7ce41614-2b91-4a44-ab8b-d11acc437960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/preceding::div[15]</value>
      <webElementGuid>5263fea4-bfec-4c0b-8bfd-38050947c26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>2a4b43cc-3f15-4c0b-b8e8-bccc41d51232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and (text() = 'Validation Error!Password required, minimum 6 characters.' or . = 'Validation Error!Password required, minimum 6 characters.')]</value>
      <webElementGuid>4accaad7-40cf-4c59-9359-c2c07d5b0436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
