<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_password</name>
   <tag></tag>
   <elementGuidId>1472b17a-4003-48eb-8d0c-c6a17a3c06af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/div[2]/main/section/form/div[3]/div/div[4]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/div[2]/main/section/form/div[3]/div/div[4]/div/div/input</value>
      <webElementGuid>a8ef9ddb-3f59-486c-bde1-85949df1ac2f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
