<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ConfirmSuccessDelete</name>
   <tag></tag>
   <elementGuidId>fb4f7533-713d-44a7-9fe0-3eeba5b72ae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0deb1e63-c3c0-4ad4-80fd-3b0de18ed482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[2]/button</value>
      <webElementGuid>1d1f6500-f4cb-4c53-be5f-c0c7202008a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
