<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PrevPage</name>
   <tag></tag>
   <elementGuidId>5b5c53d1-01aa-4f73-a945-18d97bd25c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef893cf5-652d-48a0-b0ef-4b44f3982cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[5]/div[2]/button[2]</value>
      <webElementGuid>bebe61e9-a7c2-4603-8e2b-f9d25cb56142</webElementGuid>
   </webElementProperties>
</WebElementEntity>
