<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_NextPage</name>
   <tag></tag>
   <elementGuidId>6b238f77-a1c4-4238-b3fb-dc9faafc1358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[2]/div[5]/div[2]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fb9022e-45cc-4b66-aa9b-f52885b2dfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>YSimplePagination-icon YSimplePagination-palettesecondary css-1uemjac</value>
      <webElementGuid>6524b1ed-f929-46cb-853b-1eddaff17ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-1pbasli&quot;]/div[@class=&quot;css-d3a8m4&quot;]/div[@class=&quot;YSimplePagination-root YSimplePagination-palettesecondary css-8oprbp&quot;]/button[@class=&quot;YSimplePagination-icon YSimplePagination-palettesecondary css-1uemjac&quot;]</value>
      <webElementGuid>d03992d0-e57a-4f45-abe7-15f1f56c021e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[5]/div[2]/button[3]</value>
      <webElementGuid>724ede9a-5e55-44b4-8832-af3ad2edc3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offline'])[10]/following::button[6]</value>
      <webElementGuid>6a0abea3-d8cc-4daa-8ee8-8768c4894de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offline'])[9]/following::button[9]</value>
      <webElementGuid>3e70f546-d69f-4a1a-a417-b1aa5c0ae92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert OTP'])[1]/preceding::button[2]</value>
      <webElementGuid>af0ed4cc-66fc-447d-b137-860052eb16c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::button[3]</value>
      <webElementGuid>6f7df92b-245a-471e-89e9-85eeb5bd1659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[3]</value>
      <webElementGuid>e8e40ff7-0b8f-454b-8d21-6efb0d6d041e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
