<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_GridDisplay</name>
   <tag></tag>
   <elementGuidId>80a95089-9297-4bea-987d-5830e23b5eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0490af99-6a72-493c-a8ff-78df24ecf6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]</value>
      <webElementGuid>03f70dc5-ff9c-4c9f-a462-cc19c01a0c25</webElementGuid>
   </webElementProperties>
</WebElementEntity>
