<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_GridView</name>
   <tag></tag>
   <elementGuidId>88a3fff9-cd0e-4a5c-9253-af87cd7f1040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad1c6279-68d4-4fa0-bcda-58033b27cf99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]</value>
      <webElementGuid>d8628dc7-a806-4c5a-af5a-7d9856f7c3b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
