<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_BackFromDetailDisplay</name>
   <tag></tag>
   <elementGuidId>b156be4e-305c-4703-bbd7-3057cb2ebf45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div</value>
      <webElementGuid>8f7d656e-02cc-4c60-94c2-69e37d9ab843</webElementGuid>
   </webElementProperties>
</WebElementEntity>
