<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sel_Status</name>
   <tag></tag>
   <elementGuidId>e1947bc9-0300-4473-823c-2ca44636b1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;status&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b400947-ed6b-4123-8da6-80e2707ee2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IASelect-root YInputGroup-input css-jnx7jy</value>
      <webElementGuid>57635717-ee5f-4245-9bbe-8b51348c4f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input here..</value>
      <webElementGuid>fb3e89ff-0336-4d8e-b696-990b2952c71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>aa9965db-dfd0-4ea5-8bcf-96cc59d420e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --OnlineOffline</value>
      <webElementGuid>19c22713-0d41-424f-b206-4862d75c4641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-1pbasli&quot;]/div[@class=&quot;css-kx2a0v&quot;]/div[@class=&quot;YBox-root css-87s48d&quot;]/table[@class=&quot;table css-ezcjsp&quot;]/thead[@class=&quot;table-head css-1l1lz3u&quot;]/tr[@class=&quot;table-row css-1l1lz3u&quot;]/td[@class=&quot;table-cell undefined css-1l1lz3u&quot;]/div[@class=&quot;YInputField-root  focused css-1i8wd3&quot;]/div[@class=&quot;YInputContainer&quot;]/div[@class=&quot;YInputContainer-group YInputGroup&quot;]/select[@class=&quot;IASelect-root YInputGroup-input css-jnx7jy&quot;]</value>
      <webElementGuid>af39f106-01cc-46f0-9cb8-f02e7b276ba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='status']</value>
      <webElementGuid>75537219-6a4c-40ae-96ab-c52058f3b95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[3]/div/table/thead/tr/td[4]/div/div/div/select</value>
      <webElementGuid>dbf55717-d0f8-433d-aa95-333c97a0a54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restart'])[1]/following::select[1]</value>
      <webElementGuid>0a120f6d-3df4-4eb1-be32-99cb26bb1e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screenshot'])[1]/following::select[1]</value>
      <webElementGuid>f2cedffd-292f-467e-b8b0-51c432285ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offline'])[1]/preceding::select[1]</value>
      <webElementGuid>60511428-b534-4c9e-94e1-5f6229a006a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offline'])[2]/preceding::select[1]</value>
      <webElementGuid>de93bb6e-350c-4e7f-bfb2-9e75edc7d7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b680d4e5-bd65-43b7-85a1-4b85e9a0070f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Input here..' and @name = 'status' and (text() = '-- Select --OnlineOffline' or . = '-- Select --OnlineOffline')]</value>
      <webElementGuid>64c7f065-70b8-40f7-9449-a96b6ee3e21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
