<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_EditDisplayName</name>
   <tag></tag>
   <elementGuidId>a5517ae9-e23e-431c-858c-0d9fa154a371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[2]/div[2]/div[1]/div[2]/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[2]/div[2]/div[1]/div[2]/div/div[1]/div/div/div/input</value>
      <webElementGuid>44aca457-24ca-496f-9ac9-db9d6442cb57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
