<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pop_scsupdpfp</name>
   <tag></tag>
   <elementGuidId>1c5a000a-6c21-4aaf-b7da-6eec609a7403</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[1]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[1]/p</value>
      <webElementGuid>866e7b45-63d6-4bc4-958f-894cabda120e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
