<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alt_Uploadsuccess</name>
   <tag></tag>
   <elementGuidId>3d616984-e227-4de9-9c92-72336578bcf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1kzsib</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90e5ade0-49d3-42b0-9584-80c7212abea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>26eaf3d1-081b-4c42-a83b-5bb501ca081e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1kzsib</value>
      <webElementGuid>24ff996d-e4d6-4b37-997a-2ffc00e636c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuccessFile #5STARSSMOOTHGLOW Make Over Smooth Lip Whip has been uploaded</value>
      <webElementGuid>69e117ef-d77a-4f46-baaa-64090b95b1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1jxfye&quot;]/div[@class=&quot;css-1kzsib&quot;]</value>
      <webElementGuid>d3ec8467-02e1-453d-b0cb-e34f714cd3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='success']</value>
      <webElementGuid>9d794c24-1b5c-48cb-bcdc-a8637e01ec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>3ef65a95-4dbf-41a8-865f-0add908c9e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::div[5]</value>
      <webElementGuid>2e0186a6-b2f0-4ef9-81dc-af7604f089e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>76418d5d-6203-4fa0-af26-bc316d51c344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'success' and (text() = 'SuccessFile #5STARSSMOOTHGLOW Make Over Smooth Lip Whip has been uploaded' or . = 'SuccessFile #5STARSSMOOTHGLOW Make Over Smooth Lip Whip has been uploaded')]</value>
      <webElementGuid>feb43716-35dd-4821-8030-5d47dbb66d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
