<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confirmafterdelete</name>
   <tag></tag>
   <elementGuidId>d1cba31e-9081-4312-91ae-3a8c0e07faed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13016185-c5ad-4ade-bbfc-4311c79e9dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/dialog[2]/div/div[2]/button</value>
      <webElementGuid>03663f20-ceaa-4829-9688-e1263faf5997</webElementGuid>
   </webElementProperties>
</WebElementEntity>
