<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_jumptofirstpage</name>
   <tag></tag>
   <elementGuidId>eca9aaae-d033-4b42-a7c7-5b0e91f98c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[5]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13b8e1ed-a1e8-4913-a7fc-85ed0dba2c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[5]/div[2]/button[1]</value>
      <webElementGuid>3a22a5b4-8c3c-49a3-b8d4-335e74f199e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
