<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_jumptolastpage</name>
   <tag></tag>
   <elementGuidId>0bdbfe50-b9f3-402b-82f5-2bb567dd2e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[5]/div[2]/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59259127-f89d-46fd-98c5-6d3137c2b152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[5]/div[2]/button[4]</value>
      <webElementGuid>e0f08b71-18f4-4da1-b5ae-441e1f77225f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
