<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_uploadmedia</name>
   <tag></tag>
   <elementGuidId>d246763b-1b98-4339-b260-9c0466abe520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/main/div/div[2]/div[1]/div[2]/button[1]</value>
      <webElementGuid>5430f664-e87c-4b14-8ac8-c6157b7ccab6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
