<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tb_QuickSearch</name>
   <tag></tag>
   <elementGuidId>382682f5-8c75-48f1-9171-28e404922998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/dialog[1]/div[2]/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/dialog[1]/div[2]/div/div[1]/div/div/div/input</value>
      <webElementGuid>0b9db644-ead2-491d-bcb7-96093b43e285</webElementGuid>
   </webElementProperties>
</WebElementEntity>
