<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AllDisplay</name>
   <tag></tag>
   <elementGuidId>96d18d62-e113-4633-8a46-495ab5fb253e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d41b56ed-e989-4734-8c95-9cad23660070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item total</value>
      <webElementGuid>fb5e5ca3-9c30-4585-ad9d-ddafaccf8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7+</value>
      <webElementGuid>1d9f301f-da29-476e-b6c1-9d9957019edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-fjo1i1&quot;]/div[@class=&quot;YGrid-root css-1cstzm0&quot;]/div[@class=&quot;YGridItem-root css-cfdvn5&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;total css-gr2ly1&quot;]/div[@class=&quot;YBox-root content css-87s48d&quot;]/div[@class=&quot;YBox-root content-preview css-87s48d&quot;]/div[6]/div[@class=&quot;item total&quot;]</value>
      <webElementGuid>ac8b1dee-a12b-4220-a4a3-7a975c8881e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[6]/div</value>
      <webElementGuid>fb0a3f70-41dc-4da6-9fb1-5408e0dc55c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::div[60]</value>
      <webElementGuid>99b70bb6-5148-4d01-b8df-60c73c9f4ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::div[61]</value>
      <webElementGuid>4eb2d252-e12e-47d8-b12f-dbc8c125e3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hours'])[1]/preceding::div[1]</value>
      <webElementGuid>08a06e78-41e3-48f4-8305-ba828abc0517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Days'])[1]/preceding::div[1]</value>
      <webElementGuid>e0b23d27-d49d-4c81-bec4-e8b15c735cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[6]/div</value>
      <webElementGuid>f4575b80-c927-420f-8b7e-8878165bbb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '7+' or . = '7+')]</value>
      <webElementGuid>bca89e6f-0e81-421e-a24c-0ab638bf3c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
