<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_profpic</name>
   <tag></tag>
   <elementGuidId>63a1b8ea-7683-4169-9df5-bcc748e856e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bcc3db3f-2a1f-44a3-8c8b-7b6d19c0e134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.pixelpop.interadsdev.com/locate/media/eyJpdiI6Ilc0WTJmdDRibkhFYTMxZ1BlazREaWc9PSIsInZhbHVlIjoiWTVPL3RwQ1BEUGkxZWpBOFlkUDNiQ3d1UmRVRFZVNnV2R3dtTk43N0I0MD0iLCJtYWMiOiI1NWJjNmEyODk1MzY0MDg5NjRhNjkxYjg4ODBmNjhiN2YyZTliMGIyYmFmZGVjOGFjMWEzZTM3OWRiNmE5NmM5IiwidGFnIjoiIn0=</value>
      <webElementGuid>ee5df0b2-11ca-4f7a-a72d-d0d26cfd9541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d14a232-84df-40a3-80d2-778dee798f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>85984744-7a5f-49cc-9b12-a49801587e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>4e2446e8-81fa-4ac6-a7de-8e8d18485779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>89acbd42-9795-42f9-b9ce-f8201ca82b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>915e44ab-5271-41e4-9767-19be21c33678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.pixelpop.interadsdev.com/locate/media/eyJpdiI6Ilc0WTJmdDRibkhFYTMxZ1BlazREaWc9PSIsInZhbHVlIjoiWTVPL3RwQ1BEUGkxZWpBOFlkUDNiQ3d1UmRVRFZVNnV2R3dtTk43N0I0MD0iLCJtYWMiOiI1NWJjNmEyODk1MzY0MDg5NjRhNjkxYjg4ODBmNjhiN2YyZTliMGIyYmFmZGVjOGFjMWEzZTM3OWRiNmE5NmM5IiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>7b06e17a-edc0-4025-92c4-a5b404bfa3b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
