<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_profileimage</name>
   <tag></tag>
   <elementGuidId>6f398268-6a91-4a27-bd3b-ca638577cd94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22e70866-7e82-483b-8ad4-0fee662feedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.pixelpop.interadsdev.com/locate/media/eyJpdiI6IkhFalhUMytKSnA3OFZxaXQvSS93eFE9PSIsInZhbHVlIjoiRXg4NkRocFhDS3R6NEFvQ1NEeXpyK250bnkyaGdZeWRPekZNUDFvUEhMRT0iLCJtYWMiOiJjNWNiMjI4ZjkxNmRmZDhiMjg1MTAyMDk5NzYwZGUzMDAzNGQxNGI0ZGRlYWRlODlhNmI3MmUxZWMxNTVkNTI3IiwidGFnIjoiIn0=</value>
      <webElementGuid>370f8ed1-f951-4a1e-9984-4192c13619f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>065d0f5a-cd84-45ec-954c-a1089e0554cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-1q8lbs8&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>96362277-dcb5-4e1f-9956-54704b21e335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>0c581c66-f06e-4860-bf2a-24f3ecee5e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>6e1bce2a-60b3-445c-aeeb-f040380df266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>70795d47-c902-4462-bb48-f2f0f8888dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.pixelpop.interadsdev.com/locate/media/eyJpdiI6IkhFalhUMytKSnA3OFZxaXQvSS93eFE9PSIsInZhbHVlIjoiRXg4NkRocFhDS3R6NEFvQ1NEeXpyK250bnkyaGdZeWRPekZNUDFvUEhMRT0iLCJtYWMiOiJjNWNiMjI4ZjkxNmRmZDhiMjg1MTAyMDk5NzYwZGUzMDAzNGQxNGI0ZGRlYWRlODlhNmI3MmUxZWMxNTVkNTI3IiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>b97a50f3-f0c5-4592-85ca-5d2facdaa61e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
